[workspace]
resolver = "2"
members = ["macros"]

[workspace.package]
license = "MIT"
version = "1.1.0"

[package]
name = "literateink-utilities"
version.workspace = true
authors = ["Mikkel ALMONTE--RINGAUD <mikkel@milescode.dev> (https://github.com/Vexcited)"]
readme = "README.md"
repository = "https://github.com/LiterateInk/Utilities"
description = "A general crate containing utilities for helping building our libraries."
homepage = "https://docs.literate.ink/utilities"
edition = "2021"
license.workspace = true



[dependencies]
futures = "0.3.17"
reqwest = "0.11.15"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.36"
js-sys = "0.3.63"

