[package]
name = "utilities"
version = "1.0.0"
authors = ["Mikkel ALMONTE--RINGAUD <mikkel@milescode.dev> (https://github.com/Vexcited)"]
description = "A general package containing utilities for helping building our libraries."
homepage = "https://docs.literate.ink/utilities"
edition = "2021"
repository = "https://github.com/LiterateInk/Utilities"
rust-version = "1.56"
license = "MIT"

[dependencies]
futures = "0.3.17"
reqwest = "0.11.15"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.36"
js-sys = "0.3.63"
