[package]
name = "fetcher-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
fetcher = { path = "../fetcher" }
tokio = { version = "1.0", features = ["full"] }

[lib]
proc-macro = true
